#!/bin/bash -e

setup_gopath() {
  rm -rf .gopath
  SELF="${PWD}/.gopath/src/github.com/jingweno/ccat"
  mkdir -p "${SELF%/*}"
  ln -snf "$PWD" "$SELF"
  export GOPATH="${PWD}/.gopath"
}

setup_gopath
go build -o ccat
