// Code generated by protoc-gen-go.
// source: void.proto
// DO NOT EDIT!

package pbtypes

import proto "github.com/jingweno/ccat/Godeps/_workspace/src/github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// Void is an empty type used as the protobuf RPC method arg or result
// for methods that take no parameters or yield no results,
// respectively.
type Void struct {
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}

func init() {
}
